### ISSUE TITLE
add option to hide closed notes

### ISSUE THREAD

**Issue by matkoniecz** [iandees/josm-notes#10]
I tried using this and after enabling it pollutes map with "lollolol" notes, closed a long time ago. And I see no way to hide this.

**Comment by ToeBee** [comment]
By default the API only returns closed notes that were closed within the last week. Anything that has been closed for longer than a week should not show up in this plugin. If you think this is not the case, please give some more details like where this is happening and some note IDs.

Regardless, this _is_ a feature that could be added. The option would be to change how far into the past to go on closed notes. At 0 days it would hide all closed notes.

**Comment by matkoniecz** [comment]
"By default the API only returns closed notes that were closed within the last week."

It seems quite likely, I will report bug to API operator once I discover closed note lingering for a long time.

Anyway I would be interested in feature like this - I am interested in processing notes, not in controlling process of processing notes and everything closed is not relevant for me.

**Comment by ToeBee** [comment]
This can now be controlled via an advanced preference using the built-in note handling in JOSM. Please see my blog post about how to enable this:
http://ksmapper.blogspot.com/2015/02/a-note-about-josm.html

There will be no further development on this plugin so please switch to the native note support.
