### ISSUE TITLE
Does not appear on list of available plugins in JOSM 6827

### ISSUE THREAD

**Issue by matkoniecz** [iandees/josm-notes#16]

**Comment by don-vip** [comment]
The plugin manifest is incorrect, there's an empty line after Plugin-Date

**Comment by iandees** [comment]
Manifest files are allowed to have empty lines...

**Comment by don-vip** [comment]
It seems not:
Caused by: java.io.IOException: invalid manifest format
    at java.util.jar.Manifest.read(Manifest.java:225)

**Comment by iandees** [comment]
Git started adding newlines to the end of `git show` in a recent revision, so I changed the way the build works a bit to account for that. New version should be getting scraped by josm.osm.de now.
