### ISSUE TITLE
#9858 - charset issues

### ISSUE THREAD

**Issue by don-vip** [iandees/josm-notes#21]
From https://josm.openstreetmap.de/ticket/9858

An issue is reported against wrong characters displayed for notes in czech language (on a Windows PC with czech locale).

I cannot reproduce with a French locale but it looks like a problem of character handling during parsing (something must rely on the platform default encoding instead of UTF-8).

**Comment by don-vip** [comment]
Duplicate: https://josm.openstreetmap.de/ticket/9871

**Comment by alex85k** [comment]
Seems to be fixed in JOSM itself: https://josm.openstreetmap.de/ticket/9906

**Comment by don-vip** [comment]
Notes plugin has been merged in JOSM core.
