### ISSUE TITLE
#9899 - No warning about pending uploads on exit

### ISSUE THREAD

**Issue by don-vip** [iandees/josm-notes#22]
From https://josm.openstreetmap.de/ticket/9899:

User complains of a lack of warning about still having note updates in queue and an option to upload them before exit.

**Comment by ToeBee** [comment]
Is it possible for plugins to hook into the JOSM shutdown process? The code that checks layers for unsaved changes is only looking for instances of OsmDataLayer so the notes layer won't be checked.

**Comment by don-vip** [comment]
Indeed, it wasn't possible until now:
https://josm.openstreetmap.de/changeset/7358/josm
Can you please try to implement it? You should only have to make the note layer class extend from ModifiableLayer and override the required methods.

**Comment by don-vip** [comment]
Class renamed in 7402.

**Comment by ToeBee** [comment]
Closing issue because this is handled better in the native note code.
