### ISSUE TITLE
Close on upload

### ISSUE THREAD

**Issue by norbertwenzel** [iandees/josm-notes#25]
I'd like to suggest a feature where one can work on multiple notes and mark them for closing on upload. So when the next upload is done in JOSM these notes are fixed with a comment that links to the specific changeset. At the moment I'm doing this by hand.

**Comment by don-vip** [comment]
Behaviour has changed when the plugin has been merged in JOSM core, see https://josm.openstreetmap.de/ticket/11176. This issue should be closed as the plugin is obsolete.
