### ISSUE TITLE
SAXParseException zooming out

### ISSUE THREAD

**Issue by Newbie07** [iandees/josm-notes#26]
With active online notes plugin zooming out sometimes leads to an exception. The notes layer is not rendered until you zoom in again.

See https://josm.openstreetmap.de/ticket/10202 for details

**Comment by ToeBee** [comment]
This is the result of overlapping download tasks clobbering each others input stream. If you change the viewport while the last note download is still in progress, it fires off another one using the same connection and things go bad quickly. 

While doing other improvements in the plugin I moved the download code into a runnable that gets submitted to JOSM's main worker which ensures that things are run in sequence so this won't happen any more. This change is in a branch that hasn't been merged yet but hopefully soon.

**Comment by ToeBee** [comment]
This should be fixed as of the release last night.
